--NDefines.NMilitary.MIN_BALANCE_SCORE_TO_PROCEED_ATTACK = 0.3
NDefines.NAI.MIN_NUM_CONQUERED_PROVINCES_TO_DEPRIO_NAVAL_INVADED_FRONTS = 100

NDefines.NNavy.REPAIR_AND_RETURN_AMOUNT_SHIPS_LOW = 0.1
NDefines.NNavy.REPAIR_AND_RETURN_AMOUNT_SHIPS_MEDIUM = 0.2
NDefines.NNavy.REPAIR_AND_RETURN_AMOUNT_SHIPS_HIGH = 0.3
NDefines.NNavy.REPAIR_AND_RETURN_UNIT_DYING_STR = 0.15
NDefines.NNavy.REPAIR_AND_RETURN_PRIO_MEDIUM_COMBAT = 0.2
NDefines.NNavy.REPAIR_AND_RETURN_PRIO_LOW_COMBAT = 0.4


NDefines.NAir.AI_ALLOWED_PLANES_KEPT_IN_RESERVE = 0.0
NDefines.NAI.LAND_DEFENSE_INTERCEPTORS_PER_BOMBERS = 1.4
NDefines.NAI.LAND_COMBAT_OUR_COMBATS_AIR_IMPORTANCE = 192
NDefines.NAI.AI_FRACTION_OF_FIGHTERS_RESERVED_FOR_INTERCEPTION = 0
NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_AIR_MAX_CONSUMPTION  = 15
NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_AIR_TRAINING = 3.00
NDefines.NAI.BUILDING_TARGETS_BUILDING_PRIORITIES = {
		'dockyard',
		'industrial_complex',
	}


NDefines.NAI.AIFC_CA_DIVISIONS_PER_PROVINCE = 2
NDefines.NAI.AIFC_ACTIVATE_AVG_ORG_RATIO_THRESHOLD = 0.4
NDefines.NAI.AIFC_ACTIVATE_IN_POSITION_RATIO_THRESHOLD = 0.5
NDefines.NAI.AIFC_TARGET_SUPPLY_HUB_BASE_SCORE = 35.0
NDefines.NAI.AIFC_TARGET_NAVAL_BASE_BASE_SCORE = 15.0
NDefines.NAI.AIFC_TARGET_NAVAL_BASE_SCORE_PER_LEVEL = 2.0
NDefines.NAI.AIFC_REFRESH_NEED_PER_DAY = 2.3
NDefines.NAI.AIFC_REFRESH_NEED_SUPPLY_FACTOR_PER_DAY = 1.00
NDefines.NAI.AIFC_PATH_COST_TRN_MOUNTAINS = 3.5
NDefines.NAI.AIFC_PATH_COST_TRN_MARSH = 3.5
NDefines.NAI.AIFC_PATH_COST_TRN_PLAINS = 1.15
NDefines.NAI.AIFC_PATH_COST_TRN_FOREST = 1.15
NDefines.NAI.AIFC_PATH_COST_TRN_URBAN = 0.80
NDefines.NAI.AIFC_FRESHNESS_ADD_ON_PROGRESS = 35.0
NDefines.NAI.AIFC_PATH_COST_RAILWAY_CONNECTION = 0.75
NDefines.NAI.AIFC_PATH_COST_HAS_SUPPLY_HUB = 0.50
NDefines.NAI.AIFC_TARGET_SHORT_PATH_PENALTY_FACTOR = 0.0
NDefines.NSupply.MIN_DIFF_FOR_AUTO_UPDATING_EXISTING_RAILWAYS = 2

NDefines.NAI.INDUSTRIAL_ORG_TRAIT_UNLOCK_RANDOMNESS = 1.0
NDefines.NAI.INDUSTRIAL_ORG_RESEARCH_ASSIGN_RANDOMNESS = 1.0
NDefines.NAI.INDUSTRIAL_ORG_PRODUCTION_ASSIGN_RANDOMNESS = 1.0
NDefines.NAI.CONSTRUCTION_PRIO_SUPPLY_BUILDING = 2.50
NDefines.NAI.RAIDS_CREATE_FREQUENCY_DAYS = 20
NDefines.NAI.RAIDS_COMMAND_POWER_CAP_TO_CREATE = 150.0 
NDefines.NAI.COMMAND_POWER_BEFORE_SPEND_ON_TRAITS = 50.0


NDefines.NAI.PLAN_FRONT_SECTION_MAX_LENGTH = 7
NDefines.NAI.PLAN_FRONT_SECTION_MIN_LENGTH = 4
NDefines.NAI.LOCATION_BALANCE_TO_ADVANCE = 0.0
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_LAND_DOCTRINE = 5.0
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_NAVAL_DOCTRINE = 0.5
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_AIR_DOCTRINE = 0.5
NDefines.NAI.DESIRE_USE_XP_TO_UPDATE_LAND_TEMPLATE = 15.0
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_LAND_EQUIPMENT = 5.0
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_NAVAL_EQUIPMENT = 1.0
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_AIR_EQUIPMENT = 15.0
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_ARMY_SPIRIT = 25.0
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_TEMPLATE = 7
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_EQUIPMENT = 7
NDefines.NAI.UPGRADE_DIVISION_RELUCTANCE = 3
NDefines.NAI.UPGRADE_PERCENTAGE_OF_FORCES = 0.10
NDefines.NAI.MAIN_ENEMY_FRONT_IMPORTANCE = 3.0
NDefines.NAI.VARIANT_CREATION_XP_RESERVE_LAND = 30
NDefines.NAI.DIPLOMACY_SEND_MAX_FACTION = 0.0
NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_AIR_TRAINING = -1
NDefines.NAI.RESEARCH_DAYS_BETWEEN_WEIGHT_UPDATE = 1
NDefines.NAI.RESEARCH_AHEAD_BONUS_FACTOR = 50.0
NDefines.NAI.RESEARCH_BASE_DAYS = 5000
NDefines.NAI.RESEARCH_AHEAD_OF_TIME_FACTOR = 1.1
NDefines.NAI.RESEARCH_BONUS_FACTOR = 50
NDefines.NAI.MAX_AHEAD_RESEARCH_PENALTY = 3
NDefines.NAI.RESEARCH_YEARS_BEHIND_FACTOR = 0
NDefines.NAI.RESEARCH_LENGTH_FACTOR = 3
NDefines.NAI.RESEARCH_NEEDS_FACTOR = 0.01
NDefines.NAI.MAX_SUPPLY_DIVISOR = 0.25
NDefines.NAI.FALLBACK_LOSING_FACTOR = 0.0
NDefines.NAI.DIVISION_SUPPLY_RATIO_TO_MOTORIZE = 1
NDefines.NAI.ENTRENCHMENT_WEIGHT = 2.0
NDefines.NAI.MAX_REQUEST_EXPEDITIONARIES_ARMY_RATIO = 0.0
NDefines.NAI.MIN_AI_UNITS_PER_TILE_FOR_STANDARD_COHESION = 2.0
NDefines.NAI.MIN_FRONT_SIZE_TO_CONSIDER_STANDARD_COHESION = 2000
--NDefines.NAI.MIN_FIELD_STRENGTH_TO_BUILD_UNITS = 0.75
NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.5
NDefines.NAI.MAX_MICRO_ATTACKS_PER_ORDER = 48
NDefines.NAI.MICRO_POCKET_SIZE = 3
NDefines.NAI.FRONT_CUTOFF_MIN_EDGE_PROXIMITY = 1
NDefines.NAI.PLAN_ACTIVATION_MAJOR_WEIGHT_FACTOR = 1.2
NDefines.NAI.PLAN_ACTIVATION_PLAYER_WEIGHT_FACTOR = 1
NDefines.NAI.DEPLOY_MIN_TRAINING_SURRENDER_FACTOR = 1
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_SURRENDER_FACTOR = 0.8 
NDefines.NAI.DEPLOY_MIN_TRAINING_PEACE_FACTOR = 1
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_PEACE_FACTOR = 0.9
NDefines.NAI.DEPLOY_MIN_TRAINING_WAR_FACTOR = 1
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_WAR_FACTOR = 0.9
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_CAP_DEPLOY_FACTOR = 0.85
NDefines.NAI.DOCKYARDS_PER_NAVAL_DESIRE_EFFECT = -100.0
NDefines.NAI.WANTED_UNITS_THREAT_BASE = 0.7 
NDefines.NAI.WANTED_UNITS_THREAT_MAX = 25.0
NDefines.NAI.MIN_CAPITALS_FOR_CARRIER_TASKFORCE = 12
NDefines.NAI.CAPITALS_TO_CARRIER_RATIO = 3
NDefines.NAI.SCREENS_TO_CAPITAL_RATIO = 6.0
NDefines.NAI.PLAN_STEP_COST_LIMIT = 9
NDefines.NAI.AREA_DEFENSE_BASE_IMPORTANCE = 25
NDefines.NAI.STATE_CONTROL_FOR_AREA_DEFENSE = 1.00
NDefines.NAI.LAND_DEFENSE_FIGHERS_PER_PLANE = 3
NDefines.NAI.LAND_DEFENSE_INTERSEPTORS_PER_BOMBERS = 10
NDefines.NAI.LAND_COMBAT_FIGHTERS_PER_PLANE = 3
NDefines.NAI.LAND_COMBAT_CAS_PER_COMBAT = 120
NDefines.NAI.LAND_COMBAT_CAS_PER_ENEMY_ARMY = 60
NDefines.NAI.LAND_COMBAT_ANTI_LOGISTICS_PER_ENEMY_ARMY = 0.10
NDefines.NAI.NAVAL_PATROL_PLANES_PER_SHIP_PATROLLING = 20.0
NDefines.NAI.NAVAL_PATROL_PLANES_PER_SHIP_RAIDING = 30.0
NDefines.NAI.NAVAL_PATROL_PLANES_PER_SHIP_ESCORTING = 15.0
NDefines.NAI.NAVAL_STRIKE_PLANES_PER_SHIP = 100
NDefines.NAI.DEFAULT_LEGACY_VARIANT_CREATION_XP_CUTOFF_LAND = 10
NDefines.NAI.DEFAULT_MODULE_VARIANT_CREATION_XP_CUTOFF_LAND = 20
NDefines.NAI.DEFAULT_MODULE_VARIANT_CREATION_XP_CUTOFF_NAVY = 10
NDefines.NAI.VP_LEVEL_IMPORTANCE_MEDIUM = 1
NDefines.NAI.VP_LEVEL_IMPORTANCE_LOW = 1 --keep high at 30
NDefines.NAI.PLAN_MIN_SIZE_FOR_FALLBACK = 2000
NDefines.NAI.MIN_PLAN_VALUE_TO_MICRO_INACTIVE = 0.35
NDefines.NAI.UNIT_ASSIGNMENT_TERRAIN_IMPORTANCE = 18.0
NDefines.NAI.PLAN_VALUE_TO_EXECUTE = -0.61
NDefines.NAI.FRONT_EVAL_UNIT_AIR_SUP_IMPACT = 2.0

NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 200
NDefines.NMilitary.PLAN_MIN_AUTOMATED_EMPTY_POCKET_SIZE = 15
NDefines.NMilitary.FRONT_MIN_PATH_TO_REDEPLOY = 4

NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 1
NDefines.NMilitary.PLAN_EXECUTE_CAREFUL_LIMIT = 30
NDefines.NMilitary.PLAN_EXECUTE_BALANCED_LIMIT = 0
NDefines.NMilitary.PLAN_MIN_AUTOMATED_EMPTY_POCKET_SIZE = 20
NDefines.NMilitary.FRONTLINE_EXPANSION_FACTOR = 0.4
NDefines.NMilitary.UNIT_LEADER_MODIFIER_COOLDOWN_ON_GROUP_CHANGE = 5
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0
NDefines.NDiplomacy.LICENSE_ACCEPTANCE_SAME_FACTION = 1000
NDefines.NNavy.MAX_CAPITALS_PER_AUTO_TASK_FORCE = 20
NDefines.NNavy.BEST_CAPITALS_TO_CARRIER_RATIO = 2


NDefines.NNavy.BEST_CAPITALS_TO_SCREENS_RATIO = 0.15
NDefines.NBuildings.OWNER_CHANGE_EXTRA_SHARED_SLOTS_FACTOR = 1
NDefines.NSupply.AI_FRONT_DIVISIONS_PER_SUPPLY_POINT = 0.85
NDefines.NAITheatre.AI_THEATRE_SUPPLY_CRISIS_LIMIT = 0.25
NDefines.NTrade.DISTANCE_TRADE_FACTOR = 0
NDefines.NTrade.RELATION_TRADE_FACTOR = 1.2
NDefines.NCountry.CONVOY_RANGE_FACTOR = 0.45
NDefines.NCountry.CONVOY_LENDLEASE_RANGE_FACTOR = 0.45
NDefines.NCountry.CONVOY_INTERNATIONAL_MARKET_RANGE_FACTOR = 0.45
NDefines.NAI.COMBINED_ARMS_LEVEL = 1

NDefines.NAI.MIN_NAVAL_MISSION_PRIO_TO_ASSIGN = {
		0, -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
		100, -- PATROL
		200, -- STRIKE FORCE
		200, -- CONVOY RAIDING
		200, -- CONVOY ESCORT
		200, -- MINES PLANTING
		100, -- MINES SWEEPING
		0, -- TRAIN
		0, -- RESERVE_FLEET
		100, -- NAVAL INVASION SUPPORT
	}

NDefines.NAI.HIGH_PRIO_NAVAL_MISSION_SCORES = {
		0, -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
		2000, -- PATROL
		1000, -- STRIKE FORCE
		1500, -- CONVOY RAIDING
		2000, -- CONVOY ESCORT
		-1, -- MINES PLANTING
		300, -- MINES SWEEPING
		0, -- TRAIN
		0, -- RESERVE_FLEET
		1000, -- NAVAL INVASION SUPPORT
	}

NDefines.NAI.SEA_PATH_LENGTH_SCORE_BASE = 0

NDefines.NAI.AGGRESSIVENESS_CHECK_BASE = 2.0
NDefines.NAI.AGGRESSIVENESS_CHECK_EASY_TARGET = -0.5
NDefines.NAI.AGGRESSIVENESS_CHECK_CAREFUL = 1.0	

NDefines.NAI.ASSIGN_TANKS_TO_MOUNTAINS = -15
NDefines.NAI.ASSIGN_TANKS_TO_JUNGLE = -20

NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0.3

NDefines.NAI.FAILED_INVASION_AVOID_DURATION = 180
NDefines.NAI.MIN_INVASION_PLAN_VALUE_TO_EXECUTE = 0.20
NDefines.NAI.MIN_INVASION_ORG_FACTOR_TO_EXECUTE = 0.75
NDefines.NAI.PLAN_AVG_PREPARATION_TO_EXECUTE = 0.50